import {
  grantAdmin,
  listAdmins,
  listMembers,
  revokeAdmin,
} from "@/lib/actions/admins"
import {
  addBentoOrderItem,
  closeBentoOrder,
  copyBentoOrder,
  createBentoOrder,
  deleteBentoOrder,
  getBentoOrder,
  getBentoStats,
  listBentoOrders,
  removeBentoOrderItem,
  reopenBentoOrder,
} from "@/lib/actions/bento"
import {
  createBentoRestaurant,
  deleteBentoRestaurant,
  getBentoMenuImage,
  getBentoRestaurant,
  listBentoRestaurants,
  setBentoMenu,
  setBentoMenuImage,
  setBentoOptionGroups,
  updateBentoRestaurant,
} from "@/lib/actions/bento-restaurants"
import {
  createAnnouncement,
  deleteAnnouncement,
  listAnnouncements,
  updateAnnouncement,
} from "@/lib/actions/bulletin"
import type { Action } from "@/lib/actions/define"
import { createLeave, deleteLeave, listLeaves } from "@/lib/actions/leave"
import {
  getNextMeeting,
  listMeetings,
  updateMyMeeting,
} from "@/lib/actions/meetings"
import {
  addMeeting,
  deleteMeeting,
  fillPresenters,
  generateSemester,
  setQuestioners,
  swapMeetings,
  updateMeeting,
} from "@/lib/actions/meetings-admin"
import {
  addPaper,
  addPaperTag,
  deletePaper,
  deletePaperTag,
  listPapers,
  listPaperTags,
  renamePaperTag,
  updatePaper,
} from "@/lib/actions/papers"
import {
  addPresenter,
  listPresenters,
  movePresenter,
  removePresenter,
} from "@/lib/actions/presenters"
import { getProfile } from "@/lib/actions/profile"
import {
  deleteReceipt,
  getReceiptFile,
  listReceipts,
  updateReceipt,
  uploadReceipt,
} from "@/lib/actions/receipts"
import {
  getMySignature,
  getMySignatureImage,
  setMySignature,
  setSignatureSettings,
} from "@/lib/actions/signature"
import {
  createTrip,
  deleteTrip,
  deleteTripFile,
  exportTripFiles,
  getTrip,
  getTripFile,
  getTripStats,
  listTrips,
  updateTrip,
  updateTripFile,
  uploadTripFile,
} from "@/lib/actions/trip"
import {
  addReimburseEgress,
  addReimburseIngress,
  deleteReimburseEgress,
  deleteReimburseIngress,
  getReimburseBalance,
  getReimburseStats,
  listReimburseEntries,
  updateReimburseEgress,
  updateReimburseIngress,
} from "@/lib/actions/reimburse"
import { listMeetingStats } from "@/lib/actions/stats"
import { whoami } from "@/lib/actions/users"

/** Every action, in the order MCP lists them. */
export const actions: Action[] = [
  whoami,
  getProfile,
  listLeaves,
  createLeave,
  deleteLeave,
  listAnnouncements,
  createAnnouncement,
  updateAnnouncement,
  deleteAnnouncement,
  listReceipts,
  getReceiptFile,
  uploadReceipt,
  updateReceipt,
  deleteReceipt,
  listMeetings,
  getNextMeeting,
  updateMyMeeting,
  listPapers,
  listPaperTags,
  listPresenters,
  listMeetingStats,
  generateSemester,
  addMeeting,
  updateMeeting,
  deleteMeeting,
  swapMeetings,
  fillPresenters,
  setQuestioners,
  addPaper,
  updatePaper,
  deletePaper,
  addPaperTag,
  renamePaperTag,
  deletePaperTag,
  addPresenter,
  removePresenter,
  movePresenter,
  listBentoOrders,
  getBentoOrder,
  listBentoRestaurants,
  getBentoRestaurant,
  getBentoMenuImage,
  getBentoStats,
  addBentoOrderItem,
  removeBentoOrderItem,
  copyBentoOrder,
  createBentoOrder,
  closeBentoOrder,
  reopenBentoOrder,
  deleteBentoOrder,
  createBentoRestaurant,
  updateBentoRestaurant,
  deleteBentoRestaurant,
  setBentoMenu,
  setBentoOptionGroups,
  setBentoMenuImage,
  listReimburseEntries,
  getReimburseBalance,
  getReimburseStats,
  addReimburseEgress,
  updateReimburseEgress,
  deleteReimburseEgress,
  addReimburseIngress,
  updateReimburseIngress,
  deleteReimburseIngress,
  listTrips,
  getTrip,
  getTripFile,
  exportTripFiles,
  getTripStats,
  uploadTripFile,
  updateTripFile,
  deleteTripFile,
  createTrip,
  updateTrip,
  deleteTrip,
  getMySignature,
  getMySignatureImage,
  setMySignature,
  setSignatureSettings,
  listMembers,
  listAdmins,
  grantAdmin,
  revokeAdmin,
]
